name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: cat version
        run: cat README.md
      - name: add version
        run: sed -i "s/VERSION/hoy/g" README.md
      
