name: MAIN

on:
  push:
    branches: [main]
    
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Update README.md version
        run: |
        sed -i -e "s|VERSION|1|g" README.md;
